### ISSUE TITLE
Request: End calibration by pressing a non-controller key

### ISSUE THREAD

**Issue by MrFuNK1** [Virusmater/evdev-joystick-calibration#1]
Hi,
I wanted to use the script to calibrate a device that has two axes only but no buttons. Because of that, I'm unable to end the calibration.
Any chance a "default" non-controller key can be added to end the calibration manually? Enter does already confirm the results for an axis, so maybe the whole behaviour can be changed? E.g.: "E" to exit, "C" confirm", and "R" to restart?

**Comment by Virusmater** [comment]
made few changes, can you try it out now?
now when you are done with the calibration you can press Ctrl+C and program will ask you about what to do next

**Comment by MrFuNK1** [comment]
that was too quick for me 😂 
will test ASAP, but probably not before tomorrow! surely will let you know 😉

**Comment by MrFuNK1** [comment]
Good work! That made calibrating possible for this special device, thanks!
